theme: minima
title: Hippogriff's Blog
author:
  name: Freddie Yershon
  email: hello@freddieyershon.co.uk

minima:
  # Use the custom skin defined in _sass/minima/skins/custom.scss.
  skin: custom

  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/hippogriff101"
